In [51]:
import numpy as np
from scipy import linalg as la

In [132]:
def plusol(A, b):
    p, l, u = la.lu(A)
    
    y = np.zeros((m, 1))
    c = np.dot(p, b)
    
    for j in range(m):
        y[j] = c[j] - np.dot(l[j, :j], y[:j])
    
    x = np.zeros((n, 1))
    
    for j in range(n-1, -1, -1):
        x[j] = (y[j]-np.dot(u[j, j+1:],x[j+1:]))/u[j,j]
    
    return x

In [133]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [135]:
b = np.array([[1],[1],[1]])

In [137]:
np.dot(A, plusol(A, b))

array([[1.],
       [1.],
       [1.]])

In [147]:
def determ(A):
    p, l, u = la.lu(A)
    d = la.det(p)*np.prod(np.diag(u))
    return d

In [148]:
determ(A)

6.661338147750939e-16

In [162]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2 = np.array([[1,2],[4,5],[7,8]])

In [163]:
np.dot(mat1, mat2)

array([[ 30,  36],
       [ 66,  81],
       [102, 126],
       [138, 171]])

In [169]:
def matrixmul(mat1, mat2):
    newmat = []
    for i in range(len(mat1)):
        newmati = []
        for k in range(len(mat2[0])):
            newmatik = 0
            for j in range(len(mat2)):
                newmatik += mat1[i][j]*mat2[j][k]
            newmati.append(newmatik)
        newmat.append(newmati)
    return newmat

In [168]:
matrixmul(mat1,mat2)

array([[ 30,  36],
       [ 66,  81],
       [102, 126],
       [138, 171]])